<template lang="pug">
  a-assets
    a-asset-item#fontAwesomeRegularFont(
      src="../static/fonts/Font_Awesome_Regular.json"
    )
    a-asset-item#fontAwesomeBrandsFont(
      src="../static/fonts/Font_Awesome_Brands.json"
    )
    a-asset-item#fontAwesomeSolid(
      src="../static/fonts/Font_Awesome_Solid.json"
    )
    a-asset-item#bungeeRegularFont(
      src="../static/fonts/Bungee_Regular.json"
    )
    a-asset-item#dinerSwankyRegularFont(
      src="../static/fonts/Fontdiner Swanky_Regular.json"
    )
    a-asset-item#pacificoRegularFont(
      src="../static/fonts/Pacifico_Regular.json"
    )
    a-asset-item#permanentMarkerRegularFont(
      src="../static/fonts/Permanent_Marker_Regular.json"
    )
    a-asset-item#RobotoBlackRegularFont(
      src="../static/fonts/Roboto_Black_Regular.json"
    )
    a-asset-item#RobotoRegularFont(
      src="../static/fonts/Roboto_Regular.json"
    )
    a-asset-item#tree(
      src="../static/dae/tree1.dae"
    )
    img#su1(src="static/img/su1.jpg")
    img#su2(src="static/img/su2.jpg")
    img#su3(src="static/img/su3.jpg")
    img#su4(src="static/img/su4.jpeg")
    img#su5(src="static/img/su5.png")
    img#su6(src="static/img/su6.jpg")
    img#su7(src="static/img/su7.jpg")
    img#su8(src="static/img/su8.jpg")
    img#su9(src="static/img/su9.jpg")
    img#su10(src="static/img/su10.jpg")
    img#su11(src="static/img/su11.jpg")
    img#su12(src="static/img/su12.jpg")
</template>
